### ISSUE TITLE
购物车优化

### ISSUE THREAD

**Issue by yzStrive** [iwubida/yanxuan-applet#15]
![image](https://user-images.githubusercontent.com/32640035/56638975-18e66c00-66a2-11e9-81d8-aecc646d396f.png)

**Comment by zkzhao** [comment]
这里重复是因为没有配送费优惠，当有配送费优惠的时候，下面要显示原价和优惠后的价格，产品的想法应该是在确认订单页面展示总价，需要后续和产品进一步讨论

**Comment by zkzhao** [comment]
和文静沟通后，是因为有可能购物车列表一页显示不全，造成配送费超出首屏，需要底部bar 看价格，暂不解决
