### ISSUE TITLE
地址相关需要优化的地方

### ISSUE THREAD

**Issue by yzStrive** [iwubida/yanxuan-applet#16]
![image](https://user-images.githubusercontent.com/32640035/56639064-577c2680-66a2-11e9-9f5c-1b2e9b04dc69.png)

**Comment by yzStrive** [comment]
![image](https://user-images.githubusercontent.com/32640035/56639091-6a8ef680-66a2-11e9-8cb8-dddc6573d42b.png)

**Comment by yzStrive** [comment]
![image](https://user-images.githubusercontent.com/32640035/56639096-7084d780-66a2-11e9-9113-53315dd4ff55.png)

**Comment by yzStrive** [comment]
![image](https://user-images.githubusercontent.com/32640035/56639120-82667a80-66a2-11e9-98bd-6a78c244e0c4.png)

**Comment by yzStrive** [comment]
![image](https://user-images.githubusercontent.com/32640035/56639150-94e0b400-66a2-11e9-871b-9db7ba77e36f.png)

**Comment by yzStrive** [comment]
![image](https://user-images.githubusercontent.com/32640035/56639159-9ad69500-66a2-11e9-86a4-0d69d8fdc6fb.png)

**Comment by yzStrive** [comment]
![image](https://user-images.githubusercontent.com/32640035/56639176-a45ffd00-66a2-11e9-8ea8-29d759846916.png)

**Comment by zkzhao** [comment]
@winljm001
