### ISSUE TITLE
首页加减菜品时，菜品框圆角抖动

### ISSUE THREAD

**Issue by winljm001** [iwubida/yanxuan-applet#23]
![2](https://user-images.githubusercontent.com/26362957/56874916-d2ad5600-6a6f-11e9-885d-d0280a76b0cb.gif)

首页加减菜品时，菜品框圆角抖动，当有菜品为0时触发，怀疑重新渲染了

**Comment by zkzhao** [comment]
只有模拟器会出现此问题
